config/routes.rb
Rails.application.routes.draw do

  root to: "top#index"

  get "about", to: "about#index"
  get "favorites", to: "favorites#index"

  resources :posts do
    resources :favorites, only: [:create, :destroy]
    resources :comments
  end

  devise_for :users, controllers: { sessions: "sessions", passwords: "passwords", registrations: "registrations" }
  resources :users, only: [:show]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    if params[:q]
      @search = Knowledge.ransack(params[:q])
      @knowledge = @search.result.order("updated_at DESC").page(params[:page]).per(6)
    else
      @search = Knowledge.ransack
      @knowledge = Knowledge.order("updated_at DESC").page(params[:page]).per(6)
    end
  end
end

app/views/top/_sign-in.html.erb
<div class="picture_area" style="background-image:url(/images/sign_in_image.jpg)">
  <%= link_to "Pixel Knowledge とは", about_path, class:"sign_in_link" %>
</div>
<div class="user_info">
  <div class="inner">
    <div class="user_image">
      <% if params[:id] %>
        <% if @user.user_image.present? %>
          <%= image_tag @user.user_image, alt:@user.name+"さんのアイコン画像" %>
        <% else %>
          <%= image_tag "/images/blank_icon.png" %>
        <% end %>
      <% else %>
        <% if current_user.user_image.present? %>
          <%= image_tag current_user.user_image, alt:current_user.name+"さんのアイコン画像" %>
        <% else %>
          <%= image_tag "/images/blank_icon.png" %>
        <% end %>
      <% end %>
    </div>
    <div class="user_status">
      <div class="user_name">
        <% if params[:id] %>
          <%= @user.name %>
        <% else %>
          <%= current_user.name %>
        <% end %>
      </div>
      <div>
        投稿数 :
        <% if params[:id] %>
          <%= @user.knowledges.count %>
        <% else %>
          <%= current_user.knowledges.count %>
        <% end %>
      </div>
    </div>
    <div class="user_menu">
      <%= link_to new_post_path do %>
        <i class="fa fa-pencil"></i> 投稿する
      <% end %>
      <%= link_to favorites_path do %>
        <i class="fa fa-heart-o"></i> お気に入り一覧
      <% end %>
    </div>
  </div>
</div>

app/views/top/_sign-out.html.erb
<div class="picture_area" style="background-image:url(/images/sign_out_image.jpg)">
  <%= link_to "Pixel Knowledge とは", about_path, class:"sign_out_link" %>
</div>
<div class="catchcopy">描く･添える･手順化<br>あなたの知識定着化を助けます</div>

app/views/top/index.html.erb
<% if user_signed_in? %>
  <%= render "sign-in" %>
<% else %>
  <%= render "sign-out" %>
<% end %>
<%= search_form_for(@search, url: root_path) do |f| %>
  <div class="search_form">
    <div class="inner">
      <%= f.text_field(:title_or_content_cont, class:"search_input", placeholder: "検索ワードを入力してください。") %>
      <%= button_tag sanitize('<i class="fa fa-search"></i>'), type:"submit", class:"search_btn" %>
    </div>
  </div>
<% end %>
<div class="work_list inner">
  <h2 class="contents-title">知識一覧</h2>
  <div class="knowledge_list">
    <% if @knowledge.present? %>
      <% @knowledge.each do |knowledge| %>
        <div class="knowledge_box_wrap">
          <div class="knowledge_box">
            <%= link_to post_path(knowledge.id), class:"knowledge_box_link" do %>
              <h3><%= knowledge.title %></h3>
            <% end %>
            <%= link_to image_tag(knowledge.steps.first.picture_url), post_path(knowledge.id), class:"knowledge_box_image" %>
            <div class="author_wrap">
              <span class="author_image">
                <% if knowledge.user.user_image.present? %>
                  <%= image_tag knowledge.user.user_image, alt:knowledge.user.name+"さんのアイコン画像" %>
                <% else %>
                  <%= image_tag "/images/blank_icon.png" %>
                <% end %>
              </span>
              <span class="author_name"><%= knowledge.user.name %></span>
            </div>
            <div class="create_day"><%= knowledge.updated_at.in_time_zone("Tokyo").strftime("%Y-%m-%d") %></div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="empty_alert">知識が存在しません</div>
    <% end %>
  </div>
  <%= paginate @knowledge %>
</div>