config/routes.rb
Rails.application.routes.draw do

  root to: "top#index"

  get "about", to: "about#index"
  get "favorites", to: "favorites#index"

  resources :posts do
    resources :favorites, only: [:create, :destroy]
    resources :comments
  end

  devise_for :users, controllers: { sessions: "sessions", passwords: "passwords", registrations: "registrations" }
  resources :users, only: [:show]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  # 1.イイネvsユーザー (多vs1) = 複数のイイネは1人のユーザーがしている。
  belongs_to :user
  # 4.イイネvs知識 (1vs多) = 複数のイイネは1つの知識に属している。
  belongs_to :knowledge
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    if params[:q]
      @search = current_user.favorite_knowledges.ransack(params[:q])
      @knowledge = @search.result.order("updated_at DESC").page(params[:page]).per(6)
    else
      @search = Knowledge.ransack
      @knowledge = current_user.favorite_knowledges.order("updated_at DESC").page(params[:page]).per(6)
    end
  end

  def create
    @knowledge = Knowledge.find(params[:post_id])
    @favorite = @knowledge.favorites.build
    @favorite.user_id = current_user.id
    @favorite.save
    respond_to do |format|
      format.js { render :favorites_view }
    end
  end

  def destroy
    @knowledge = Knowledge.find(params[:post_id])
    @favorite = Favorite.find(params[:id])
    @favorite.destroy
    respond_to do |format|
      format.js { render :favorites_view }
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/favorites_view.js.erb
<% if action_name == "create" %>
  $(".knowledge_good").html('<%= link_to post_favorite_path(@favorite.knowledge_id, @favorite.id), method: :delete, remote: true do %><i class="fa fa-heart"></i> いいね解除 <span><%= @knowledge.favorites.count %></span>件<% end %>');
<% else %>
  $(".knowledge_good").html('<%= link_to post_favorites_path(@knowledge.id), method: :post, remote: true do %><i class="fa fa-heart"></i> いいね <span><%= @knowledge.favorites.count %></span>件<% end %>');
<% end %>

app/views/favorites/index.html.erb
<% if user_signed_in? %>
  <%= render "top/sign-in" %>
<% else %>
  <%= render "top/sign-out" %>
<% end %>
<%= search_form_for(@search, url: favorites_path) do |f| %>
  <div class="search_form">
    <div class="inner">
      <%= f.text_field(:title_or_content_cont, class:"search_input", placeholder: "検索ワードを入力してください。") %>
      <%= button_tag sanitize('<i class="fa fa-search"></i>'), type:"submit", class:"search_btn" %>
    </div>
  </div>
<% end %>
<div class="work_list inner">
  <h2 class="contents-title">お気に入り一覧</h2>
  <div class="knowledge_list">
    <% if @knowledge.present? %>
      <% @knowledge.each do |knowledge| %>
        <div class="knowledge_box_wrap">
          <div class="knowledge_box">
            <%= link_to post_path(knowledge.id), class:"knowledge_box_link" do %>
              <h3><%= knowledge.title %></h3>
            <% end %>
            <%= link_to image_tag(knowledge.steps.first.picture_url), post_path(knowledge.id), class:"knowledge_box_image" %>
            <div class="author_wrap">
              <span class="author_image">
                <% if knowledge.user.user_image.present? %>
                  <%= image_tag knowledge.user.user_image, alt:knowledge.user.name+"さんのアイコン画像" %>
                <% else %>
                  <%= image_tag "/images/blank_icon.png" %>
                <% end %>
              </span>
              <span class="author_name"><%= knowledge.user.name %></span>
            </div>
            <div class="create_day"><%= knowledge.updated_at.in_time_zone("Tokyo").strftime("%Y-%m-%d") %></div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="empty_alert">お気に入りの知識が存在しません</div>
    <% end %>
  </div>
  <%= paginate @knowledge %>
</div>