config/routes.rb
Rails.application.routes.draw do

  root to: "top#index"

  get "about", to: "about#index"
  get "favorites", to: "favorites#index"

  resources :posts do
    resources :favorites, only: [:create, :destroy]
    resources :comments
  end

  devise_for :users, controllers: { sessions: "sessions", passwords: "passwords", registrations: "registrations" }
  resources :users, only: [:show]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: { maximum: 140 }

  # 5.コメントvsユーザー (多vs1) = 複数のコメントは1人のユーザーが投稿している。
  belongs_to :user
  # 6.コメントvs知識 (多vs1) = 複数のコメントは1つの知識に属している。
  belongs_to :knowledge
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @knowledge = Knowledge.find(params[:post_id])
    @comments = @knowledge.comments
    respond_to do |format|
      format.js { render :comments_reload }
    end
  end

  def create
    @knowledge = Knowledge.find(params[:post_id])
    @comment = @knowledge.comments.build(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.js { render :comments_reload }
      else
        format.js { render :comment_error }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.js { render :comments_reload }
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    respond_to do |format|
      format.js { render :comment_edit }
    end
  end

  def update
    @comment = Comment.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.js { render :comments_reload }
      else
        format.js { render :comment_error }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :knowledge_id, :user_id)
  end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/comments/_edit.html.erb
<div class="comment_user_name"><%= comment.user.name %></div>
<%= form_with(model: comment, url: post_comment_path(comment.knowledge_id, comment.id), remote: true) do |f| %>
  <div class="comment_edit_form">
    <%= f.text_area(:content, class:"canvas_l_input") %>
    <div class="error_line"></div>
    <div>
      <%= link_to "キャンセル", post_comments_path, class:"btn btn-default submit_btn", remote: true %>
      <%= f.submit "保存する", class:"btn btn-default submit_btn" %>
    </div>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul class="comment_list">
  <% if comments.present? %>
    <% comments.each do |comment| %>
      <li id="comment<%= comment.id %>" class="comment_item">
        <div class="comment_user_image">
          <% if comment.user.user_image.present? %>
            <%= image_tag comment.user.user_image, alt:comment.user.name+"さんのアイコン画像" %>
          <% else %>
            <%= image_tag "/images/blank_icon.png" %>
          <% end %>
        </div>
        <div class="comment_user_status">
          <div class="comment_user_name"><%= comment.user.name %></div>
          <div class="comment_text"><%= comment.content %></div>
          <div class="comment_create_day"><%= comment.created_at.in_time_zone("Tokyo").strftime("%Y-%m-%d %H:%M:%S") %></div>
          <% if comment.user == current_user %>
            <div class="comment_links">
              <%= link_to "編集する", edit_post_comment_path(comment.knowledge_id, comment.id), remote: true %>・<%= link_to "削除する", post_comment_path(comment.knowledge_id, comment.id), data: { title: "削除の確認", confirm: "コメントを削除しますか？", cancel: "閉じる", commit: "削除する" }, method: :delete, remote: true %>
            </div>
          <% end %>
        </div>
      </li>
    <% end %>
  <% else %>
    <div class="empty_alert">コメントが存在しません</div>
  <% end %>
</ul>

app/views/comments/comment_edit.js.erb
$("#comment<%= @comment.id %> .comment_user_status").html('<%= j(render "edit", { comment: @comment }) %>');

app/views/comments/comment_error.js.erb
<% if action_name == "create" %>
  // create
  $(".comment_form .canvas_l_input").css("border-color","#f00");
  $(".comment_form .error_line").html("<%= @comment.errors.full_messages_for(:content)[0] %>");
<% else %>
  // update
  $(".comment_edit_form .canvas_l_input").css("border-color","#f00");
  $(".comment_edit_form .error_line").html("<%= @comment.errors.full_messages_for(:content)[0] %>");
<% end %>

app/views/comments/comments_reload.js.erb
<% if @comments %>
  // index
  $(".comment_edit_form .canvas_l_input").css("border-color","#e5e5e5");
  $(".comment_edit_form .error_line").html("");
  $(".comment_list").html('<%= j(render "index", { comments: @comments }) %>');
<% else %>
  // create destroy update
  $(".comment_form .canvas_l_input").css("border-color","#e5e5e5");
  $(".comment_form .error_line").html("");
  $(".comment_list").html('<%= j(render "index", { comments: @comment.knowledge.comments }) %>');
  $(".comment_form .canvas_l_input").val("");
<% end %>