config/routes.rb
Rails.application.routes.draw do

  root to: "top#index"

  get "about", to: "about#index"
  get "favorites", to: "favorites#index"

  resources :posts do
    resources :favorites, only: [:create, :destroy]
    resources :comments
  end

  devise_for :users, controllers: { sessions: "sessions", passwords: "passwords", registrations: "registrations" }
  resources :users, only: [:show]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include CarrierwaveBase64Uploader
  before_action :authenticate_user!, except: [:show]
  before_action :set_knowledge, only: [:show, :edit, :update, :destroy]

  def new
    @knowledge = Knowledge.new
    @knowledge.steps.build
    gon.steps = ""
  end

  def create
    @knowledge = Knowledge.new(knowledge_params)
    if params["knowledge"]["title"] == ""
      @knowledge.title = "無題"
    end
    @knowledge.user_id = current_user.id
    step_count = params["step"].to_i
    for i in 0..step_count-1 do
      @knowledge.steps_attributes = {i:{picture: base64_conversion(params["picture"+i.to_s],"step"+i.to_s+Time.now.strftime("%Y%m%d%H%M%S").to_s), comment: params["comment"+i.to_s], canvas_obj: params["canvas"+i.to_s]}}
    end
    respond_to do |format|
      if @knowledge.save
        flash[:notice] = "知識を投稿しました。"
        format.js { render js: "window.location.replace('#{root_path}');"}
      end
    end
  end

  def show
    @comments = @knowledge.comments
    if user_signed_in?
      @favorite = current_user.favorites.find_by(knowledge_id: @knowledge.id)
      @comment = Comment.new
    end
  end

  def edit
    if current_user.id == @knowledge.user_id
      gon.steps = @knowledge.steps.order("id DESC")
    else
      redirect_back(fallback_location: post_path(@knowledge.id))
    end
  end

  def update
    if params["knowledge"]["title"] == ""
      @knowledge.title = "無題"
    end
    step_count = params["step"].to_i
    for i in 0..step_count-1 do
      @knowledge.steps_attributes = {i:{id: params["id"+i.to_s], picture: base64_conversion(params["picture"+i.to_s],"step"+i.to_s+Time.now.strftime("%Y%m%d%H%M%S").to_s), comment: params["comment"+i.to_s], canvas_obj: params["canvas"+i.to_s]}}
    end
    respond_to do |format|
      if @knowledge.update(knowledge_params)
        flash[:notice] = "知識を更新しました。"
        format.js { render js: "window.location.replace('#{root_path}');"}
      end
    end
  end

  def destroy
    @knowledge.destroy
    redirect_to root_path, notice: "知識を削除しました。"
  end

  private

  def set_knowledge
    @knowledge = Knowledge.find(params[:id])
  end

  def knowledge_params
    params.require(:knowledge).permit(:title, :content, :user_id, steps_attributes: [:id, :picture, :comment])
  end
end

app/views/posts/edit.html.erb
<%= form_with(model: @knowledge, url: post_path(@knowledge.id), id:"knowledge_update_form", remote: true) do |f| %>
  <div class="canvas_area inner">
    <div class="canvas_active_area">
      <ul>
        <li class="modal_sign_item">
          <%= f.label :title %>
        </li>
        <li>
          <%= f.text_field(:title, class:"canvas_l_input title_input", maxlength:"50") %>
        </li>
      </ul>
      <ul class="modal_sign_item">
        <li class="modal_sign_item">
          <%= f.label :content %>
        </li>
        <li>
          <%= f.text_area(:content, class:"canvas_l_input content_input", maxlength:"200") %>
        </li>
      </ul>
      <canvas id="my_canvas" height="500" width="800" ></canvas>
      <div class="btn btn-default submit_btn" onclick="update_post_canvas()">更新する</div>
    </div>
    <div class="canvas_select_area">
      <ul class="canvas_modes">
        <li class="modal_sign_item">モード</li>
        <li class="btn btn-default btn-sm user_tooltip select_mode" data-toggle="tooltip" title="選択モード" onclick="mode_ch_canvas(false)"><i class="fa fa-mouse-pointer"></i></li>
        <li class="btn btn-default btn-sm user_tooltip draw_mode" data-toggle="tooltip" title="描画モード" onclick="mode_ch_canvas(true)"><i class="fa fa-pencil"></i></li>
        <div class="btn-group">
          <button type="button" class="dropdown-toggle btn-default btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            線の太さ: <span>細</span>
          </button>
          <ul class="dropdown-menu">
            <li><a>細</a></li>
            <li><a>中</a></li>
            <li><a>太</a></li>
          </ul>
        </div>
        <input type="text" maxlength="7" class="form-control draw_colorpicker">
      </ul>
    </div>
    <div class="canvas_select_area">
      <ul>
        <li class="modal_sign_item">テキスト挿入</li>
        <li><textarea id="canvas_textbox" class="canvas_r_input insert_text_input" maxlength="50"></textarea></li>
        <div class="btn btn-default btn-sm" onclick="text_insert()">挿入する</div>
        <div class="btn-group">
          <button type="button" class="dropdown-toggle btn-default btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            サイズ: <span>14</span>px
          </button>
          <ul class="dropdown-menu">
            <li><a>14</a></li>
            <li><a>15</a></li>
            <li><a>16</a></li>
            <li><a>17</a></li>
            <li><a>18</a></li>
            <li><a>19</a></li>
            <li><a>20</a></li>
            <li><a>21</a></li>
            <li><a>22</a></li>
            <li><a>23</a></li>
            <li><a>24</a></li>
            <li><a>25</a></li>
            <li><a>26</a></li>
            <li><a>27</a></li>
            <li><a>28</a></li>
            <li><a>29</a></li>
            <li><a>30</a></li>
            <li><a>31</a></li>
            <li><a>32</a></li>
            <li><a>33</a></li>
            <li><a>34</a></li>
          </ul>
        </div>
        <input type="text" maxlength="7" class="form-control select_text_colorpicker">
      </ul>
    </div>
    <div class="canvas_select_area">
      <ul>
        <li class="modal_sign_item">画像挿入</li>
        <label class="upload_image" for="canvas_image">
          <span class="upload_image_name">画像を選択する</span>
          <input type="file" id="canvas_image" style="display:none;">
        </label>
        <div class="btn btn-default btn-sm" onclick="image_insert()">挿入する</div>
      </ul>
      <canvas id="resize_canvas" style="display:none;"></canvas>
    </div>
    <div class="canvas_select_area">
      <ul>
        <li class="modal_sign_item">コメント</li>
        <li><textarea id="knowledge_comment" class="canvas_r_input comment_input" maxlength="100"></textarea></li>
      </ul>
      <div class="canvas_step">
        <div class="step_bar">
          <div class="btn btn-default btn-sm" onclick="update_prev_canvas()">戻る</div>
          <div class="btn btn-default btn-sm" onclick="update_canvas()">更新</div>
          <div class="btn btn-default btn-sm" onclick="update_next_canvas()">進む</div>
          <div class="step_num"><span class="step_current_num"></span> / <span class="step_max_num"></span> ステップ</div>
        </div>
        <ul class="step_images"></ul>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<%= form_with(model: @knowledge, url: posts_path, id:"knowledge_form", remote: true) do |f| %>
  <div class="canvas_area inner">
    <div class="canvas_active_area">
      <ul>
        <li class="modal_sign_item">
          <%= f.label :title %>
        <li>
          <%= f.text_field(:title, class:"canvas_l_input title_input", maxlength:"50") %>
        </li>
      </ul>
      <ul class="modal_sign_item">
        <li class="modal_sign_item">
          <%= f.label :content %>
        </li>
        <li>
          <%= f.text_area(:content, class:"canvas_l_input content_input", maxlength:"200") %>
        </li>
      </ul>
      <canvas id="my_canvas" height="500" width="800" ></canvas>
      <div class="btn btn-default submit_btn" onclick="post_canvas()">投稿する</div>
    </div>
    <div class="canvas_select_area">
      <ul class="canvas_tools">
        <li class="modal_sign_item">モード</li>
        <li class="btn btn-default btn-sm user_tooltip" data-toggle="tooltip" title="選択モード" onclick="mode_ch_canvas(false)"><i class="fa fa-mouse-pointer"></i></li>
        <li class="btn btn-default btn-sm user_tooltip" data-toggle="tooltip" title="描画モード" onclick="mode_ch_canvas(true)"><i class="fa fa-pencil"></i></li>
        <div class="btn-group">
          <button type="button" class="dropdown-toggle btn-default btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            線の太さ: <span>細</span>
          </button>
          <ul class="dropdown-menu ">
            <li><a>細</a></li>
            <li><a>中</a></li>
            <li><a>太</a></li>
          </ul>
        </div>
        <input type="text" maxlength="7" class="form-control draw_colorpicker">
      </ul>
    </div>
    <div class="canvas_select_area">
      <ul>
        <li class="modal_sign_item">テキスト挿入</li>
        <li><textarea id="canvas_textbox" class="canvas_r_input insert_text_input" maxlength="50"></textarea></li>
        <div class="btn btn-default btn-sm" onclick="text_insert()">挿入する</div>
        <div class="btn-group">
          <button type="button" class="dropdown-toggle btn-default btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            サイズ: <span>14</span>px
          </button>
          <ul class="dropdown-menu">
            <li><a>14</a></li>
            <li><a>15</a></li>
            <li><a>16</a></li>
            <li><a>17</a></li>
            <li><a>18</a></li>
            <li><a>19</a></li>
            <li><a>20</a></li>
            <li><a>21</a></li>
            <li><a>22</a></li>
            <li><a>23</a></li>
            <li><a>24</a></li>
            <li><a>25</a></li>
            <li><a>26</a></li>
            <li><a>27</a></li>
            <li><a>28</a></li>
            <li><a>29</a></li>
            <li><a>30</a></li>
            <li><a>31</a></li>
            <li><a>32</a></li>
            <li><a>33</a></li>
            <li><a>34</a></li>
          </ul>
        </div>
        <input type="text" maxlength="7" class="form-control select_text_colorpicker">
      </ul>
    </div>
    <div class="canvas_select_area">
      <ul>
        <li class="modal_sign_item">画像挿入</li>
        <label class="upload_image" for="canvas_image">
          <span class="upload_image_name">画像を選択する</span>
          <input type="file" id="canvas_image" style="display:none;">
        </label>
        <div class="btn btn-default btn-sm" onclick="image_insert()">挿入する</div>
      </ul>
      <canvas id="resize_canvas" style="display:none;"></canvas>
    </div>
    <div class="canvas_select_area">
      <ul>
        <li class="modal_sign_item">コメント</li>
        <li><textarea id="knowledge_comment" class="canvas_r_input comment_input" maxlength="100"></textarea></li>
      </ul>
      <div class="canvas_step">
        <div class="step_bar">
          <div class="btn btn-default btn-sm" onclick="prev_canvas()">戻る</div>
          <div class="btn btn-default btn-sm" onclick="save_canvas()">記録</div>
          <div class="btn btn-default btn-sm" onclick="next_canvas()">進む</div>
          <div class="step_num"><span class="step_current_num">0</span> / 9 ステップ</div>
        </div>
        <ul class="step_images"></ul>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="show_area">
  <div class="show_area_wrap">
    <div class="knowledge_info_area">
      <div class="user_image">
        <% if @knowledge.user.user_image.present? %>
          <%= image_tag @knowledge.user.user_image, alt:@knowledge.user.name+"さんのアイコン画像" %>
        <% else %>
          <%= image_tag "/images/blank_icon.png" %>
        <% end %>
      </div>
      <div class="user_status">
        <div class="user_name">
          <% if user_signed_in? %>
            <%= link_to @knowledge.user.name, user_path(@knowledge.user.id) %>
          <% else %>
            <%= @knowledge.user.name %>
          <% end %>
        </div>
        <div>投稿数 : <%= @knowledge.user.knowledges.count %></div>
      </div>
      <h2 class="knowledge_title"><%= @knowledge.title %></h2>
      <div class="knowledge_content"><%= @knowledge.content %></div>
    </div>
    <ul class="bxslider">
      <% @knowledge.steps.order("id DESC").each{|step, i| %>
        <li>
          <%= image_tag step.picture_url, alt:"さんのアイコン画像" %>
          <span class="knowledge_step_comment"><%= step.comment %></span>
        </li>
      <% } %>
    </ul>
    <div class="knowledge_option_area">
      <div class="knowledge_good">
        <% if user_signed_in? && @knowledge.user.id != current_user.id %>
          <% if @favorite.present? %>
            <%= link_to post_favorite_path(@favorite.knowledge_id, @favorite.id), method: :delete, remote: true do %>
              <i class="fa fa-heart"></i> いいね解除 <span><%= @knowledge.favorites.count %></span>件
            <% end %>
          <% else %>
            <%= link_to post_favorites_path(@knowledge.id), method: :post, remote: true do %>
              <i class="fa fa-heart"></i> いいね <span><%= @knowledge.favorites.count %></span>件
            <% end %>
          <% end %>
        <% else %>
          <i class="fa fa-heart"></i> いいね <%= @knowledge.favorites.count %>件
        <% end %>
      </div>
      <% if user_signed_in? && @knowledge.user.id == current_user.id %>
        <div class="knowledge_links">
          <%= link_to "編集する", edit_post_path(@knowledge.id) %>・<%= link_to "削除する", post_path(@knowledge.id), data: { title: "削除の確認", confirm: "知識を削除しますか？", cancel: "閉じる", commit: "削除する" }, method: :delete %>
        </div>
      <% end %>
    </div>
    <div class="knowledge_comment_area">
      <h3>コメント</h3>
      <%= render partial: "comments/index", locals: { comments: @comments } %>
      <% if user_signed_in? %>
        <%= form_with(model: @comment, url: post_comments_path(@knowledge.id), method: :post, remote: true) do |f| %>
          <div class="comment_form">
            <%= f.text_area(:content, class:"canvas_l_input") %>
            <div class="error_line"></div>
            <%= f.submit "コメントを投稿する", class:"btn btn-default submit_btn" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>